### ISSUE TITLE
thinning error

### ISSUE THREAD

**Issue by buhl22** [05dirnbe/nefi#45]
I tried again to install nefi from source on ubuntu and i got the gui to run. but when i try to run a pipeline i get the follow error:
libpng warning: iCCP: known incorrect sRGB profile
Adding a QLayout to a QSplitter is not supported.
Set modified
Set modified
Set modified
Set modified
Start pipeline at 0
UnSet modified
Current cat <segmentation.CatBody object at 0x7f94d3e585c0>
Failed to process pipeline
Traceback (most recent call last):
  File "/home/buhl/.nefi2/nefi2/view/main_controller.py", line 1883, in run
    self.pipeline.process()
  File "/home/buhl/.nefi2/nefi2/model/pipeline.py", line 297, in process
    cat.process(data)
  File "/home/buhl/.nefi2/nefi2/model/categories/_category.py", line 136, in process
    selected_alg.process(args)
  File "nefi2/model/algorithms/thinning.py", line 50, in process
    skeleton = thinning.guo_hall_thinning(args[0].copy())
AttributeError: module 'thinning' has no attribute 'guo_hall_thinning'

i am quite certain that i installed the thinning algorithm as indicated  in guide

**Comment by tastyminerals** [comment]
rename `thinning.py` into `thinning_alg.py`

**Comment by buhl22** [comment]
okay that fixed the error thank you.
But now no images seem to be saved nor folders created. do i ahve to modify more code. Or rename at other places

**Comment by tastyminerals** [comment]
If you see the results on the left pane of **nefi2**, they are saved.
By default the processing results are saved into `nefi/output` dir unless explicitly set by user.
If you don't see any results in the left pane **after** you click "Run" button, you'll need to explain in a separate issue how to reproduce this error.
