### ISSUE TITLE
Cannot run nefi-mac_64bit_build on Mac OSX High Sierra

### ISSUE THREAD

**Issue by arumakanorat** [05dirnbe/nefi#49]
Hi,

I could download the nefi-mac_64bit_build. however could not run the NEFI on my mac, OSX High Sierra with some error. Please see the below error message that I got. I did work through the installation guide of the web. http://nefi.mpi-inf.mpg.de/documentation. Do you have any idea to fix it? 

My environment
-Mac OSX High Sierra
-Python 3.6.5
-import statements went through

Thanks in advance!

```$ /Applications/nefi-mac_64bit_build/NEFI ; exit;
Traceback (most recent call last):
  File "/Applications/nefi-mac_64bit_build/nefi2/view/main_controller.py", line 35, in <module>
    base, form = uic.loadUiType(mainview_path)
  File ":/PyQt5/uic/__init__.pyo", line 198, in loadUiType
  File ":/PyQt5/uic/Compiler/compiler.pyo", line 110, in compileUi
  File ":/PyQt5/uic/uiparser.pyo", line 992, in parse
  File ":/xml/etree/ElementTree.py", line 1182, in parse
  File ":/xml/etree/ElementTree.py", line 583, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'nefi2/view/MainView.ui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nefi2.py", line 8, in <module>
  File "bootstrap.py", line 969, in _find_and_load
  File "bootstrap.py", line 958, in _find_and_load_unlocked
  File "bootstrap.py", line 673, in _load_unlocked
  File "bootstrap_external.py", line 662, in exec_module
  File "bootstrap.py", line 222, in _call_with_frames_removed
  File "/Applications/nefi-mac_64bit_build/nefi2/main.py", line 12, in <module>
    from nefi2.view.main_controller import MainView
  File "bootstrap.py", line 969, in _find_and_load
  File "bootstrap.py", line 958, in _find_and_load_unlocked
  File "bootstrap.py", line 673, in _load_unlocked
  File "bootstrap_external.py", line 662, in exec_module
  File "bootstrap.py", line 222, in _call_with_frames_removed
  File "/Applications/nefi-mac_64bit_build/nefi2/view/main_controller.py", line 37, in <module>
    raise NameError(os.listdir(os.curdir))
NameError: ['.docker', '.bash', '.anyconnect', '.ActivePerl', '.DS_Store', ...etc... FOLDER LIST]
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by tastyminerals** [comment]
I think that these builds are long outdated by now and should not be used anymore. Try and run `nefi2.py` directly, it should work as long as you have all the dependencies installed.

**Comment by arumakanorat** [comment]
Thanks @tastyminerals ,

I got an another error, `Segmentation fault: 11` just like below when I tried running `nefi2.py` directly. Do you have any idea to fix it?
```
$ python nefi2.py
Segmentation fault: 11
```
I _think_ I got all the dependencies.
```
$ python
Python 3.6.5 (default, Jun 11 2018, 14:40:28) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> import numpy
>>> import demjson
>>> import PyQt5
>>> import cv2
>>> 
```

**Comment by tastyminerals** [comment]
This should be MacOS related, take a look https://github.com/ageitgey/face_recognition/issues/83

Also, make sure you run `python3 nefi2.py`.
